# Pandas
Pandas is a powerful and flexible open-source data analysis and manipulation library for Python. It provides data structures like Series and DataFrame, which are designed to handle structured data efficiently. Pandas is widely used in data science, machine learning, and statistical analysis.

In [1]:
import numpy as np
import pandas as pd

# Pandas Series
A Pandas Series is a one-dimensional labeled array that can hold data of any type (integer, float, string, etc.). Each element in a Series is associated with an index, which allows for easy access and manipulation of the data.

## How we should visualize the pandas series in our mind
- A Pandas Series can be visualized as a single column of data with an associated index
- The index can be thought of as the "row labels" for the data, while the values represent the actual data points in that column.

# Pandas DataFrame
A Pandas DataFrame is a two-dimensional labeled data structure that can hold data of different types (integer, float, string, etc.) in columns. It is similar to a spreadsheet or SQL table and is one of the most commonly used data structures in Pandas.

## How we should visualize the pandas dataframe in our mind
- A Pandas DataFrame can be visualized as a table with rows and columns, where each column can hold data of a different type. The rows represent individual records, while the columns represent different features or attributes of the data.
|----------|----------|----------|----------|
|          | Column 1 | Column 2 | Column 3 |
|----------|----------|----------|----------|
| Row 1    | Value 1  | Value 2  | Value 3  |
|----------|----------|----------|----------|
| Row 2    | Value 4  | Value 5  | Value 6  |
|----------|----------|----------|----------|
| Row 3    | Value 7  | Value 8  | Value 9  |
|----------|----------|----------|----------|

In [2]:
info = {
    "Name": ["Zeon", "Sojib", "Samiul", "Kamal", "Riaz"],
    "CGPA": [3.8, 3.7, 3.9, 3.3, 3.6],
}
print("Info:", info);
df = pd.DataFrame(info)
print("DataFrame:")
print(df)

Info: {'Name': ['Zeon', 'Sojib', 'Samiul', 'Kamal', 'Riaz'], 'CGPA': [3.8, 3.7, 3.9, 3.3, 3.6]}
DataFrame:
     Name  CGPA
0    Zeon   3.8
1   Sojib   3.7
2  Samiul   3.9
3   Kamal   3.3
4    Riaz   3.6

In [3]:
# Series in pandas
s = pd.Series([23, 24, 25, 26])
print(s)
print(type(s)) # <class 'pandas.core.series.Series'>

# Indexing
print(s[0])    # 23
print(s[2])    # 25

print(s.index)     # all labels

# Custom Indexing
s2 = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Charlie", "Bob"])
print(s2["Eve"])    # 24
print(s2["Bob"])    # 26

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

print(s1 + s2)

# Mutable Values but immutable size
s = pd.Series([1, 2, 3, 4, 5])
s[0] = 100

print(s)

changed_s = s.drop(1)
print(changed_s)
print(s)

0    23
1    24
2    25
3    26
dtype: int64
<class 'pandas.Series'>
23
25
RangeIndex(start=0, stop=4, step=1)
24
26
0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [4]:
s = pd.Series([1, 3, 5, 7, 9], index = ["a", "b", "c", "d", "e"])
print(s)

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [5]:
print(s["a"])   # Label-based indexing
print(s["c"])

print(s.iloc[0])  # Position-based indexing
print(s.iloc[2])

print(s.index)

1
5
1
5
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

## Series Properties
1. Homogeneous
    - All elements in a Series are of the same data type (e.g., all integers, all floats, all strings).
    - If one element is of a different type, Pandas will attempt to upcast the entire Series to a common data type that can accommodate all elements.
    - This ensures that the Series maintains a consistent data type throughout its lifetime.
    - example: If you create a Series with integers and floats, Pandas will upcast the integers to floats to maintain homogeneity. If you create a Series with integers and strings, Pandas will upcast the integers to objects.
2. Vectorized Operations
    - Pandas Series supports vectorized operations, which means that you can perform operations on the entire Series without the need for explicit loops. This allows for efficient and concise code when working with large datasets.
    - For example, you can add two Series together in a single operation, rather than having to iterate through each element individually.
    - This makes it easy to perform complex calculations on large datasets quickly and efficiently.
3. Handles Missing Data with NaN
    - Pandas Series can handle missing data using the special value NaN (Not a Number). This allows for easy identification and handling of missing values in your data.
    - You can use methods like `isna()` and `fillna()` to identify and fill missing values in a Series, respectively.
4. Mutable values, but immutable size
    - The values in a Pandas Series can be modified, but the size of the Series (i.e., the number of elements) is fixed once it is created. This means that you can change the values of existing elements, but you cannot add or remove elements from the Series after it has been created.
    - If we add or remove elements from a Series, a new Series will be created with the updated size, rather than modifying the original Series in place. This ensures that the original Series remains unchanged and can be used for reference or comparison later on.

In [6]:
# DataFrame in pandas
info = {
    "Name": ["Zeon", "Sojib", "Samiul", "Kamal", "Riaz"],
    "CGPA": [3.8, 3.7, 3.9, 3.3, 3.6],
    "Age": [22, 23, 21, 24, 25]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

     Name  CGPA  Age
0    Zeon   3.8   22
1   Sojib   3.7   23
2  Samiul   3.9   21
3   Kamal   3.3   24
4    Riaz   3.6   25
RangeIndex(start=0, stop=5, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='str')

In [7]:
# Creating DataFrame from a list of lists
df = pd.DataFrame([["Zeon", 3.8, 22], ["Sojib", 3.7, 23], ["Samiul", 3.9, 21], ["Kamal", 3.3, 24], ["Riaz", 3.6, 25]], columns=["Name", "CGPA", "Age"])
df

     Name  CGPA  Age
0    Zeon   3.8   22
1   Sojib   3.7   23
2  Samiul   3.9   21
3   Kamal   3.3   24
4    Riaz   3.6   25

In [8]:
# Creating DataFrame from a numpy array
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_array, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
# read csv file
df = pd.read_csv("employee_data.csv")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

In [10]:
# read json file
df = pd.read_json("employee_data.json")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.DataFrame'>

### DataFrame methods
1. `head(n)`: Returns the first n rows of the DataFrame.
2. `tail(n)`: Returns the last n rows of the DataFrame.
3. `info()`: Provides a concise summary of the DataFrame.
4. `describe()`: Generates descriptive statistics for the DataFrame.
5. `shape`: Returns a tuple representing the dimensions of the DataFrame.
6. `columns`: Returns the column labels of the DataFrame.
7. `dtypes`: Returns the data types of each column in the DataFrame.
8. `values`: Returns the underlying numpy array of the DataFrame.
9. `set_index()`: Sets the index of the DataFrame to a specified column.
10. `reset_index()`: Resets the index of the DataFrame to default values.
11. `sample(n)`: Returns a random sample of n rows from the DataFrame.
12. `nunique()`: Returns the number of unique values in each column of the DataFrame.

In [11]:
# print(df.head())  # first 5 rows
# print(df.tail())  # last 5 rows
# print(df.sample(5))  # random 5 rows
# df.info()  # summary of the DataFrame
# df.shape # Returns a tuple representing the dimensionality of the DataFrame (rows, columns)
# df.describe() # summary statistics of the DataFrame
# df.columns # Returns the column labels of the DataFrame
df.nunique() # Returns the number of unique values for each column in the DataFrame

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [12]:
df = pd.read_csv("globalAirQuality.csv")
df.head()
df.tail()
df.describe()
df.info()
df.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  str
 1   country      18000 non-null  str
 2   city         18000 non-null  str
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 2.1 MB

timestamp        360
country           38
city              50
latitude          50
longitude         50
pm25           15839
pm10           16332
no2            15139
so2             8158
o3             15275
co              1376
aqi              178
temperature    13930
humidity       15725
wind_speed      8058
dtype: int64

In [13]:
# Selecting data
# Selecting columns
df['city']  # Select a single column
df[['city', 'aqi']]  # Select multiple columns

# Selecting rows
df.iloc[0]  # Select a single row by index
df.iloc[0:5]  # Select multiple rows by index range
df.loc[0:5]  # Select multiple rows by index range (inclusive of the last index)

# Selecting rows and columns
df.loc[0:5, ['city', 'aqi']]  # Select specific rows and columns

df.iloc[0:6, 1:5]  # Select specific rows and columns by index

df.at[0, 'city']  # Select a single value by row and column labels
df.iat[0, 1]  # Select a single value by row and column indices

cities = df['city'].copy()
print(cities)
cities[0] = 'Dhaka'
print(cities)

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str
0           Dhaka
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [14]:
# Filtering of data
df[ df["aqi"] > 100 ]  # Filter rows where aqi > 100

df[ (df["aqi"] > 100) & (df["temperature"] > 30) ]  # Filter rows where aqi > 100 and temperature > 30

df[ (df["aqi"] > 100) & (df["temperature"] < 30) ]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ][["city", "aqi"]]

# aqi_data.iloc[0]
aqi_data.loc[6]

# Query
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]

aqi_val = 150
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
44     New York  156
112    New York  192
284    New York  151
329    New York  167
...         ...  ...
17589  Helsinki  160
17665    Zurich  167
17797    Zurich  170
17821    Zurich  166
17822    Zurich  167

[185 rows x 2 columns]

### Cleaning of data

- Handling missing values
- `isnull() / isna()`: Returns a boolean Series indicating whether each value is missing (NaN).
- `isnull().sum()`: Returns the count of missing values in each column of the DataFrame.
- `dropna()`: Removes rows or columns with missing values from the DataFrame.
- `fillna(value)`: Fills missing values in the DataFrame with a specified value or method (e.g., forward fill, backward fill).
- `ffill()`: Fills missing values using the last valid observation (forward fill).
- `bfill()`: Fills missing values using the next valid observation (backward fill).

In [15]:
# Cleaning of data
raw_data = pd.read_csv("raw_data.csv")

raw_data.isnull()
raw_data.isna()
raw_data.isnull().sum()  # Count of missing values in each column
raw_data.dropna()  # Remove rows with missing values
raw_data.dropna(axis=1)  # Remove columns with missing values
raw_data.fillna(0)  # Fill missing values with 0
cleaned_data = raw_data.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)  # Fill missing values in 'age' column with mean
cleaned_data

raw_data.ffill()  # Forward fill missing values
raw_data.bfill()  # Backward fill missing values

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [16]:
# Handle duplicates
raw_data.duplicated() # Returns a boolean Series indicating duplicate rows
unique_data = raw_data.copy()
unique_data.drop_duplicates(inplace=True) # Remove duplicate rows and modify the original DataFrame in place
unique_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [17]:
# Data Types
raw_data.dtypes

rd = raw_data.copy()
avg_age = rd["age"].mean()
rd = rd.fillna(0)
rd["age"] = rd["age"].astype("int64").copy()
rd.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [18]:
aqi_data = df.copy()
aqi_data.columns
aqi_data.dtypes
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])  # Convert 'timestamp' column to datetime type
aqi_data.dtypes

timestamp      datetime64[us]
country                   str
city                      str
latitude              float64
longitude             float64
pm25                  float64
pm10                  float64
no2                   float64
so2                   float64
o3                    float64
co                    float64
aqi                     int64
temperature           float64
humidity              float64
wind_speed            float64
dtype: object

In [19]:
rd["gender"].str.upper()

rd["name"].str.split(" ")

rd["country"].str.contains("usa", case=False)  # Case-insensitive search for 'usa' in 'country' column

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [20]:
# Feature Engineering

# apply()
rd["tax"] = rd["income"].apply(lambda x: "20%" if x > 50000 else "10%")  # Apply a function to create a new column 'tax' based on 'income'

# map()
# Male => M, Female => F, Unknown => U
gender_mapping = {"Male": "M", "Female": "F", "Unknown": "U"}
rd["gender"] = rd["gender"].map(gender_mapping)

# assign()
rd = rd.assign(new_income = rd["income"] * 1.1) # Create a new column 'new_income' by increasing 'income' by 10%

# replace(old_value, new_value)
rd["country"] = rd["country"].replace("USA", "US")

# rename(columns={"old_name": "new_name"}) Change column names
# rename(index={"old_index": "new_index"}) Change Row (index) names
rd.rename(columns={"name": "full_name", "income": "salary"})
rd.rename(index={0: "row_0", 1: "row_1"})

rd.sort_values("income")
rd.sort_values("income", ascending=False)
sorted_rd = rd.sort_values(["income", "age"])

sorted_rd.sort_index()

# reset
sorted_rd.reset_index()
sorted_rd.reset_index(drop=True)  # Reset index and drop the old index

# ranking
sorted_rd["income_rank"] = sorted_rd["income"].rank(ascending=False, method="dense")  # Rank the 'income' column in descending order

# Reorder columns
sorted_rd[["id", "name", "age", "country", "gender", "income", "new_income", "income_rank", "tax"]]

,id,name,age,country,gender,income,new_income,income_rank,tax
4,4,Maria Garcia,34,Spain,F,0.0,0.0,9.0,10%
9,9,Carlos Ruiz,0,Mexico,M,45000.0,49500.0,8.0,10%
3,3,Alex,0,US,U,47000.0,51700.0,7.0,10%
5,5,Li Wei,27,China,M,51000.0,56100.0,6.0,20%
0,1,John Doe,29,US,M,55000.0,60500.0,5.0,20%
1,1,John Doe,29,US,M,55000.0,60500.0,5.0,20%
10,10,Emily Davis,31,US,NaN,58000.0,63800.0,4.0,20%
2,2,Jane Smith,0,Canada,F,62000.0,68200.0,3.0,20%
8,8,Rachel Lee,29,US,F,62000.0,68200.0,3.0,20%
7,7,Ahmed Khan,38,0,M,68000.0,74800.0,2.0,20%
6,6,0,45,India,F,73000.0,80300.0,1.0,20%

In [21]:
# Shift id column to the end
td = raw_data.copy()
# td = td[["name", "age", "country", "gender", "income", "id"]]
new_columns_order = [col for col in td.columns if col != "id"] + ["id"]
td = td[new_columns_order]
td

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [22]:
# clean the raw data and save it to a new csv file
cd = raw_data.copy()
cd = cd.drop_duplicates()
age_mean = cd["age"].mean()
cd["age"] = cd["age"].fillna(age_mean)
cd["age"] = cd["age"].astype("int64")
cd["gender"] = cd["gender"].fillna("Unknown")
cd["name"] = cd["name"].fillna("Unknown")
cd["income"] = cd["income"].fillna(0)
cd = cd.sort_values("income", ascending=False)
cd.sort_index(inplace=True)
cd.to_csv("cleaned_data.csv", index=False)

In [23]:
raw_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [27]:
# Concatanation and Merging of DataFrames

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ["Zeon", "Sojib", "Samiul"]
})
df2 = pd.DataFrame({
    'id': [4, 5, 6],
    'name': ["Kamal", "Riaz", "Nabil"]
})

pd.concat([df1, df2]) # row-wise concatenation
pd.concat([df1, df2], ignore_index=True) # row-wise concatenation with new index
pd.concat([df1, df2], axis=1) # column-wise concatenation

   id    name  id   name
0   1    Zeon   4  Kamal
1   2   Sojib   5   Riaz
2   3  Samiul   6  Nabil

In [41]:
raw_data.groupby("country")["income"].mean()  # Group by 'country' and calculate mean of 'income'
raw_data.groupby("gender")["income"].max()
raw_data.groupby("country").agg({"income": "mean", "age": "max"})  # Group by 'country' and calculate mean of 'income' and max of 'age'
raw_data.groupby("country")["income"].agg(["mean", "max", "min", "count"])  # Group by 'country' and calculate mean, max, min, and count of 'income'

raw_data.groupby("country").agg(max_salary=("income", "max"), average_age=("age", "mean"))  # Group by 'country' and calculate max of 'income' and mean of 'age'

         max_salary  average_age
country
Canada      62000.0          NaN
China       51000.0         27.0
India       73000.0         45.0
Mexico      45000.0          NaN
Spain           NaN         34.0
USA         62000.0         29.5